apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: www-prod
  name: prod
  labels:
    monitoring: prod
spec:
  selector:
    matchLabels:
      env: prod
  podMetricsEndpoints:
    - port: metrics
