apiVersion: v1
kind: Namespace
metadata:
    name: www-test
    labels:
        env: test
---
apiVersion: v1
kind: Namespace
metadata:
    name: www-prod
    labels:
        env: prod
---
apiVersion: v1
kind: Namespace
metadata:
    name: monitoring
